# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_remove_feature_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
