# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20160312_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_num',
        ),
        migrations.AddField(
            model_name='item',
            name='purchase_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='PurchaseNum',
        ),
    ]
