# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_auto_20160312_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.IntegerField(default=0),
        ),
    ]
