# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_remove_feature_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='ticket.Client'),
        ),
    ]
