# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_item_purchase_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
    ]
