# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-12 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_item_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sale_place',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
