# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_item_sale_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sale_price',
            new_name='sold_price',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='item',
            name='date_target',
        ),
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
        migrations.RemoveField(
            model_name='item',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='item',
            name='url',
        ),
        migrations.AddField(
            model_name='item',
            name='carat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_bought',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='date_sold',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='metal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='stone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sale_place',
            field=models.CharField(choices=[('Unsold', 'Unsold'), ('Grays', 'Grays'), ('Ebay', 'Ebay')], default='Unsold', max_length=50),
        ),
    ]
