# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20160313_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='face_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='notes',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
