# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0008_auto_20160301_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
