# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_currency_exchangerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangerate',
            old_name='name',
            new_name='rate',
        ),
    ]
