# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_auto_20160408_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
