# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_item_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='ExchangeRate',
        ),
        migrations.RemoveField(
            model_name='item',
            name='rate',
        ),
    ]
