# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-08 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20160408_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditSelected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkbox', models.BooleanField()),
            ],
        ),
    ]
